################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy realtime-sensing --compose-file docker-compose.yml
# docker-compose -f docker-compose.yml -p realtime-sensing up
################################################################################
version: "3.7"

services:

  node-red:
    image: node-red-realtime-sensing
    restart: always
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    networks:
      - realtime-sensing-net
    volumes:
      - node-red-data:/data

  mongo:
    image: mongo
    restart: always
    networks:
      - realtime-sensing-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test_password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - realtime-sensing-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test_password
      ME_CONFIG_MONGODB_URL: mongodb://root:test_password@mongo:27017
    volumes:
      - mongo-data:/data



volumes:
  node-red-data:
  mongo-data:

networks:
  realtime-sensing-net:
